### ISSUE TITLE
KALSR ISSUE (again)

### ISSUE THREAD

**Issue by Ic3bu7g** [Crafttino21/PS4Rootkit#2]
I tried linux aswell, it still crashes on that part, defeating kaslr

**Comment by Crafttino21** [comment]
1st: What PS4 Modell you have?
2st: Did you restart your console and try it again?

**Comment by Ic3bu7g** [comment]
After my ps4 crashes and boots up again, after it boots up should i restart?

**Comment by Ic3bu7g** [comment]
if yes, then ill do that, if not ill try figure out the model

**Comment by Crafttino21** [comment]
Just shut it down, wait a few seconds and start it again. Normally your ps4 should start a "check filesystem" scan and that can take some time. But it should work after this

**Comment by Ic3bu7g** [comment]
alright bro ill do

**Comment by Ic3bu7g** [comment]
wait is that checking system storage status, or something differnet?

**Comment by Crafttino21** [comment]
Yea. It should pop up after pressing start

**Comment by Ic3bu7g** [comment]
yes that happened, i tried it, it crashedm the cycle repeats

**Comment by Crafttino21** [comment]
Have you done a full shutdown? If yes do it again and pull out the Power cable for like 5 Seconds. than start it again

**Comment by Ic3bu7g** [comment]
what do you mean by a *full shutdown*

**Comment by Crafttino21** [comment]
Go to power options > press shutdown (not restart, Not Saving mode) and wait until your LES turns off. Than Pull out your Power cable and wait some seconds. than plug it in and restart via pushing the power button on your PS4

**Comment by Ic3bu7g** [comment]
LES?

**Comment by Crafttino21** [comment]
LED i am sorry haha

**Comment by Ic3bu7g** [comment]
oh on the ps4?

**Comment by Crafttino21** [comment]
Yea. Based on your model you have a LED Stripe or 5 LED Dots on the power button

**Comment by Ic3bu7g** [comment]
argh crashed again, gonna try again

**Comment by Crafttino21** [comment]
Normally it should not crash. Thats the problem haha. Maybe is your console broken? With the PPPwn Launcher from Modded warfare i have the problem that it Stuckls on CPU Pinning 93% and with the original Linux version i have mostly "find corrupted data failed" and after some trys it works so i dont have any crashes :')

What Firmware do you use?

**Comment by Ic3bu7g** [comment]
i am on 1100, i also have the issue with modded warfare on t he 93% (for verson 1.1), on 1.2 i t was like a 50/50% chance then it fails on scanning for corrupted object, how would my console be broken?

**Comment by Ic3bu7g** [comment]
yup it keeps on crashing :(

**Comment by Ic3bu7g** [comment]
man i waited years for this :(

**Comment by Ic3bu7g** [comment]
is there ANY way at all i can fix it

**Comment by Crafttino21** [comment]
> i am on 1100, i also have the issue with modded warfare on t he 93% (for verson 1.1), on 1.2 i t was like a 50/50% chance then it fails on scanning for corrupted object, how would my console be broken?

This with corrupted objects is normal. I have the same problem but on some lucky tries it works

> is there ANY way at all i can fix it

I cant tell you that because i also dont know were the problem happens :')

**Comment by Ic3bu7g** [comment]
ok, i appreciate your help
